---
- hosts: all
  vars:
    ansible_host_key_checking: false ##If you get an error about hosts not trusted
  become: yes
  become_user: root

  tasks:
    - name: Update all installed packages using APT module
      apt:
        name: '*'
        state: latest
        update_cache: yes
        only_upgrade: yes
        register: apt_update_status
    - name: Remove packages not needed anymore
      apt:
        autoremove: yes
    - name: Reboot when packages were updated
      reboot:
        post_reboot_delay: 60
        when: apt_update_status.changed
