---
- hosts: all
  vars:
    ansible_host_key_checking: false ##If you get an error about hosts not trusted
  become: yes
  become_user: root

  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
